# Generated by Django 4.1.7 on 2023-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_rename_names_userinfo_username_remove_userinfo_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=32, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=32, verbose_name="用户名"),
        ),
    ]
