# Generated by Django 4.1.7 on 2023-04-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_news_newsdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news", old_name="news_num", new_name="comments_num",
        ),
    ]
