# Generated by Django 4.1.7 on 2023-04-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_rename_news_num_news_comments_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_hot", models.IntegerField(verbose_name="热度")),
                ("word", models.CharField(max_length=128, verbose_name="标题")),
                ("category", models.CharField(max_length=32, verbose_name="类别")),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_writer", models.CharField(max_length=64, verbose_name="博主")),
                ("text_time", models.CharField(max_length=64, verbose_name="发表时间")),
                ("text_forward_num", models.IntegerField(verbose_name="转发数")),
                ("text_comment_num", models.IntegerField(verbose_name="评论数")),
                ("text_like_num", models.IntegerField(verbose_name="点赞数")),
                ("text_content", models.TextField(verbose_name="文章内容")),
                ("text_url", models.CharField(max_length=128, verbose_name="文章地址")),
            ],
        ),
        migrations.RenameField(
            model_name="news", old_name="comments_num", new_name="news_num",
        ),
    ]
