# Generated by Django 4.1.7 on 2023-04-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_hotsearch_text_rename_comments_num_news_news_num"),
    ]

    operations = [
        migrations.DeleteModel(name="HotSearch",),
        migrations.RemoveField(model_name="newsdata", name="news",),
        migrations.DeleteModel(name="Text",),
        migrations.DeleteModel(name="News",),
        migrations.DeleteModel(name="NewsData",),
    ]
