# Generated by Django 4.1.7 on 2023-04-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_delete_hotsearch_remove_newsdata_news_delete_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_text_url",
                    models.CharField(max_length=128, verbose_name="文章地址"),
                ),
                ("comment_writer", models.CharField(max_length=64, verbose_name="博主")),
                ("comment_time", models.CharField(max_length=64, verbose_name="发表时间")),
                ("total_num", models.IntegerField(verbose_name="评论数")),
                ("comment_like_num", models.IntegerField(verbose_name="点赞数")),
                ("comment_content", models.TextField(verbose_name="评论内容")),
                (
                    "comment_source",
                    models.CharField(max_length=64, verbose_name="博主位置"),
                ),
                ("text_word", models.CharField(max_length=128, verbose_name="标题")),
            ],
        ),
        migrations.CreateModel(
            name="HotSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_hot", models.IntegerField(verbose_name="热度")),
                (
                    "word",
                    models.CharField(max_length=128, unique=True, verbose_name="标题"),
                ),
                ("category", models.CharField(max_length=32, verbose_name="类别")),
                ("ontime", models.CharField(max_length=64, verbose_name="在榜时间")),
            ],
        ),
        migrations.CreateModel(
            name="Select",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(default=1, verbose_name="选择事件序号")),
            ],
        ),
        migrations.CreateModel(
            name="SpiderTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new",
                    models.CharField(
                        default="2099-12-01", max_length=64, verbose_name="最近时间"
                    ),
                ),
                (
                    "old",
                    models.CharField(
                        default="0000-01-01", max_length=64, verbose_name="最晚时间"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_writer", models.CharField(max_length=64, verbose_name="博主")),
                ("text_word", models.CharField(max_length=128, verbose_name="标题")),
                ("text_time", models.CharField(max_length=64, verbose_name="发表时间")),
                ("text_forward_num", models.IntegerField(verbose_name="转发数")),
                ("text_comment_num", models.IntegerField(verbose_name="评论数")),
                ("text_like_num", models.IntegerField(verbose_name="点赞数")),
                ("text_content", models.TextField(verbose_name="文章内容")),
                (
                    "text_url",
                    models.CharField(max_length=128, unique=True, verbose_name="文章地址"),
                ),
            ],
        ),
    ]
