# Generated by Django 4.1.7 on 2023-04-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_comment_hotsearch_select_spidertime_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum_positive", models.IntegerField(verbose_name="积极评论数")),
                ("sum_negtive", models.IntegerField(verbose_name="消极评论数")),
            ],
        ),
    ]
