# Generated by Django 4.1.7 on 2023-04-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0009_emotion"),
    ]

    operations = [
        migrations.DeleteModel(name="Emotion",),
    ]
