# Generated by Django 4.1.7 on 2023-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0012_delete_emotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e_id", models.IntegerField(verbose_name="评论数id")),
                ("sum_positive", models.IntegerField(verbose_name="积极评论数")),
                ("sum_negtive", models.IntegerField(verbose_name="消极评论数")),
                ("sum_positive1", models.IntegerField(verbose_name="积极评论数")),
                ("sum_negtive1", models.IntegerField(verbose_name="消极评论数")),
            ],
        ),
    ]
